version: '3.8'
services:
  server:
    image: server_image
    build: ./shareIt-server
    container_name: server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ShareIt
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
  db:
    image: postgres:14.3-alpine
    container_name: db
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ShareIt
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
  gateway:
    image: gateway_image
    build: ./shareIt-gateway
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
