CREATE TABLE IF NOT EXISTS Users
(
    id    int8 GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name  VARCHAR(30),
    email VARCHAR(50),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS Items
(
    id           int8 GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name         VARCHAR(40),
    description  TEXT,
    is_available BOOLEAN DEFAULT TRUE,
    request_id   int8,
    owner_id     int8 REFERENCES Users (id)
);

CREATE TABLE IF NOT EXISTS Bookings
(
    id         int8 GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP,
    end_date   TIMESTAMP,
    item_id    int8 REFERENCES Items (id),
    booker_id  int8 REFERENCES Users (id),
    status     VARCHAR(15)
);

CREATE TABLE iF NOT EXISTS Requests
(
    id           int8 GENERATED BY DEFAULT AS IDENTITY,
    description  TEXT,
    requestor_id int8 REFERENCES Users (id)
);

CREATE TABLE IF NOT EXISTS Comments
(
    id int8 GENERATED BY DEFAULT AS IDENTITY,
    text TEXT,
    item_id int8 REFERENCES Items(id),
    author_id int8 REFERENCES Users(id)
);
